## Dragon Real Estate - Price Predictor

In [1]:
import pandas as pd

In [2]:
housing = pd.read_csv("data.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       501 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
housing["CHAS"].value_counts()

CHAS
0    471
1     35
Name: count, dtype: int64

In [6]:
housing.CHAS.value_counts()

CHAS
0    471
1     35
Name: count, dtype: int64

In [7]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284341   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.705587   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

# Missing values filling

In [8]:
# We can 
# 1. Drop missing rows
# 2. Drop entire column
# 3. Fill the values with (0, mean, median)

In [9]:
# We'll try filling valaues with two ways 1st with median and then mean

### FillNA with Median

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
imputer = SimpleImputer(strategy="median")

In [12]:
housing.RM.isna().sum()

5

In [13]:
housing_data = housing.copy()

In [14]:
imputer.fit(housing_data)

SimpleImputer(strategy='median')

In [15]:
imputer.statistics_

array([2.56510e-01, 0.00000e+00, 9.69000e+00, 0.00000e+00, 5.38000e-01,
       6.20800e+00, 7.75000e+01, 3.20745e+00, 5.00000e+00, 3.30000e+02,
       1.90500e+01, 3.91440e+02, 1.13600e+01, 2.12000e+01])

In [16]:
Data = imputer.transform(housing_data)

In [17]:
housing_tranformed = pd.DataFrame(Data, columns=housing_data.columns)

In [18]:
housing_tranformed

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [19]:
housing_tranformed.RM.isna().sum()

0

### FillNA with Mean

In [20]:
housing

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [21]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284341   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.705587   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [22]:
housing.RM.value_counts()

RM
6.405    3
6.229    3
6.167    3
5.713    3
6.127    3
        ..
6.020    1
6.546    1
5.859    1
6.416    1
6.976    1
Name: count, Length: 441, dtype: int64

In [23]:
housing.RM.isna().sum()

5

In [24]:
avgRM = housing.RM.mean()
avgRM

6.28434131736527

In [25]:
housing.RM.fillna(avgRM,inplace = True)
housing

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [26]:
housing.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [27]:
# We have seen we filled NA with Mean and Median as well.
# Now we're referrring transfomred data moving onwords

In [28]:
housing = housing_tranformed

In [29]:
# %matplotlib inline
# import matplotlib as plt
# housing.hist(bins = 50, figsize=(25,30))

## Train Test Splitting

In [30]:
import numpy as np
def split_train_test(data,test_ratio):
    
    np.random.seed(42) ## This will fixed randomizing data again and again. Only 1st time data will randomlly selected.
    
    shuffled = np.random.permutation(len(data)) ## This will randomally selects data from dataset.
    
    test_size = int(len(data) * test_ratio)
    train_indices = shuffled[test_size:]
    test_indices = shuffled[:test_size]
    return data.iloc[train_indices], data.iloc[test_indices]

In [31]:
train_data, test_data = split_train_test(housing,0.2)

In [32]:
print(f'''Number of rows in train dataset: {len(train_data)}
Number of rows in test dataset: {len(test_data)}''')

Number of rows in train dataset: 405
Number of rows in test dataset: 101


In [33]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(housing, test_size = .2, random_state = 42)

In [34]:
print(f'''Number of rows in train dataset: {len(train)}
Number of rows in test dataset: {len(test)}''')

Number of rows in train dataset: 404
Number of rows in test dataset: 102


In [35]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits = 1,test_size = .2,random_state= 42)

for train_index,test_index in split.split(housing,housing["CHAS"]):
    strat_test_index = housing.loc[test_index]
    strat_train_index = housing.loc[train_index]

In [36]:
strat_test_index

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
342   0.02498   0.0   1.89   0.0  0.518  6.540   59.7  6.2669   1.0  422.0   
379  17.86670   0.0  18.10   0.0  0.671  6.223  100.0  1.3861  24.0  666.0   
223   0.61470   0.0   6.20   0.0  0.507  6.618   80.8  3.2721   8.0  307.0   
219   0.11425   0.0  13.89   1.0  0.550  6.373   92.4  3.3633   5.0  276.0   
48    0.25387   0.0   6.91   0.0  0.448  5.399   95.3  5.8700   3.0  233.0   
..        ...   ...    ...   ...    ...    ...    ...     ...   ...    ...   
88    0.05660   0.0   3.41   0.0  0.489  7.007   86.3  3.4217   2.0  270.0   
466   3.77498   0.0  18.10   0.0  0.655  5.952   84.7  2.8715  24.0  666.0   
52    0.05360  21.0   5.64   0.0  0.439  6.511   21.1  6.8147   4.0  243.0   
121   0.07165   0.0  25.65   0.0  0.581  6.004   84.1  2.1974   2.0  188.0   
218   0.11069   0.0  13.89   1.0  0.550  5.951   93.8  2.8893   5.0  276.0   

     PTRATIO       B  LSTAT  MEDV  
342     15.9  389.96   8.65  16.5  
379     20.2  393.74  21.78  10.2  
223     17.4  396.90   7.60  30.1  
219     16.4  393.74  10.50  23.0  
48      17.9  396.90  30.81  14.4  
..       ...     ...    ...   ...  
88      17.8  396.90   5.50  23.6  
466     20.2   22.01  17.15  19.0  
52      16.8  396.90   5.28  25.0  
121     19.1  377.67  14.27  20.3  
218     16.4  396.90  17.92  21.5  

[102 rows x 14 columns]

In [37]:
strat_train_index

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
254  0.04819  80.0   3.64   0.0  0.392  6.108  32.0  9.2203   1.0  315.0   
348  0.01501  80.0   2.01   0.0  0.435  6.635  29.7  8.3440   4.0  280.0   
476  4.87141   0.0  18.10   0.0  0.614  6.484  93.6  2.3053  24.0  666.0   
321  0.18159   0.0   7.38   0.0  0.493  6.376  54.3  4.5404   5.0  287.0   
326  0.30347   0.0   7.38   0.0  0.493  6.312  28.9  5.4159   5.0  287.0   
..       ...   ...    ...   ...    ...    ...   ...     ...   ...    ...   
155  3.53501   0.0  19.58   1.0  0.871  6.152  82.6  1.7455   5.0  403.0   
423  7.05042   0.0  18.10   0.0  0.614  6.103  85.1  2.0218  24.0  666.0   
98   0.08187   0.0   2.89   0.0  0.445  7.820  36.9  3.4952   2.0  276.0   
455  4.75237   0.0  18.10   0.0  0.713  6.525  86.5  2.4358  24.0  666.0   
216  0.04560   0.0  13.89   1.0  0.550  5.888  56.0  3.1121   5.0  276.0   

     PTRATIO       B  LSTAT  MEDV  
254     16.4  392.89   6.57  21.9  
348     17.0  390.94   5.99  24.5  
476     20.2  396.21  18.68  16.7  
321     19.6  396.90   6.87  23.1  
326     19.6  396.90   6.15  23.0  
..       ...     ...    ...   ...  
155     14.7   88.01  15.02  15.6  
423     20.2    2.52  23.29  13.4  
98      18.0  393.53   3.57  43.8  
455     20.2   50.92  18.13  14.1  
216     16.4  392.80  13.51  23.3  

[404 rows x 14 columns]

In [38]:
strat_test_index.CHAS.value_counts()

CHAS
0.0    95
1.0     7
Name: count, dtype: int64

In [39]:
strat_train_index.CHAS.value_counts()

CHAS
0.0    376
1.0     28
Name: count, dtype: int64

In [40]:
376/28

13.428571428571429

In [41]:
95/7

13.571428571428571

In [42]:
housing= strat_train_index.copy()

## Correlation

In [43]:
corr_matrix = housing.corr()

# corr_marix["MEDV"].sort_values(ascending = False)

# ## Strong Positive Corrilation = 1
# # Strong Negative Corrilation = -1

In [44]:
corr_matrix

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.212927  0.416640 -0.061482  0.430879 -0.256843  0.361890   
ZN      -0.212927  1.000000 -0.542161 -0.023536 -0.509327  0.292010 -0.565680   
INDUS    0.416640 -0.542161  1.000000  0.043686  0.759051 -0.382166  0.644114   
CHAS    -0.061482 -0.023536  0.043686  1.000000  0.077490  0.100672  0.058388   
NOX      0.430879 -0.509327  0.759051  0.077490  1.000000 -0.299416  0.727358   
RM      -0.256843  0.292010 -0.382166  0.100672 -0.299416  1.000000 -0.240747   
AGE      0.361890 -0.565680  0.644114  0.058388  0.727358 -0.240747  1.000000   
DIS     -0.386900  0.666939 -0.708612 -0.088081 -0.763623  0.202010 -0.734827   
RAD      0.648221 -0.306480  0.580908 -0.023005  0.596012 -0.198916  0.449489   
TAX      0.603934 -0.322803  0.716288 -0.048802  0.659049 -0.280938  0.501491   
PTRATIO  0.305603 -0.390570  0.384465 -0.132682  0.164977 -0.329776  0.259633   
B       -0.486869  0.188575 -0.368685  0.048275 -0.408434  0.121794 -0.287900   
LSTAT    0.471442 -0.420097  0.611068 -0.077592  0.602386 -0.601693  0.599211   
MEDV    -0.393715  0.339741 -0.473516  0.205066 -0.422873  0.680262 -0.364596   

              DIS       RAD       TAX   PTRATIO         B     LSTAT      MEDV  
CRIM    -0.386900  0.648221  0.603934  0.305603 -0.486869  0.471442 -0.393715  
ZN       0.666939 -0.306480 -0.322803 -0.390570  0.188575 -0.420097  0.339741  
INDUS   -0.708612  0.580908  0.716288  0.384465 -0.368685  0.611068 -0.473516  
CHAS    -0.088081 -0.023005 -0.048802 -0.132682  0.048275 -0.077592  0.205066  
NOX     -0.763623  0.596012  0.659049  0.164977 -0.408434  0.602386 -0.422873  
RM       0.202010 -0.198916 -0.280938 -0.329776  0.121794 -0.601693  0.680262  
AGE     -0.734827  0.449489  0.501491  0.259633 -0.287900  0.599211 -0.364596  
DIS      1.000000 -0.481556 -0.530840 -0.215173  0.309222 -0.501408  0.240451  
RAD     -0.481556  1.000000  0.910932  0.471912 -0.490951  0.479857 -0.374693  
TAX     -0.530840  0.910932  1.000000  0.473026 -0.475293  0.534228 -0.456657  
PTRATIO -0.215173  0.471912  0.473026  1.000000 -0.193293  0.370759 -0.493534  
B        0.309222 -0.490951 -0.475293 -0.193293  1.000000 -0.405799  0.361761  
LSTAT   -0.501408  0.479857  0.534228  0.370759 -0.405799  1.000000 -0.740494  
MEDV     0.240451 -0.374693 -0.456657 -0.493534  0.361761 -0.740494  1.000000

In [45]:
corr_matrix["MEDV"].sort_values(ascending = False)

## Strong Positive Corrilation = 1
## Strong Negative Corrilation = -1

MEDV       1.000000
RM         0.680262
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [46]:
from pandas.plotting import scatter_matrix

In [47]:
att_list = ["MEDV","RM","ZN","LSTAT"]

In [48]:
# scatter_matrix(housing[att_list],figsize=(20,9))

In [49]:
# housing.plot(kind="scatter",x = "RM", y = "MEDV", alpha = 1)

## Try out Attribute combination 

In [50]:
housing["TPRM"] = housing["TAX"]/housing["RM"]

In [51]:
housing["TPRM"] 

254     51.571709
348     42.200452
476    102.714374
321     45.012547
326     45.468948
          ...    
155     65.507152
423    109.126659
98      35.294118
455    102.068966
216     46.875000
Name: TPRM, Length: 404, dtype: float64

In [52]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
254  0.04819  80.0   3.64   0.0  0.392  6.108  32.0  9.2203   1.0  315.0   
348  0.01501  80.0   2.01   0.0  0.435  6.635  29.7  8.3440   4.0  280.0   
476  4.87141   0.0  18.10   0.0  0.614  6.484  93.6  2.3053  24.0  666.0   
321  0.18159   0.0   7.38   0.0  0.493  6.376  54.3  4.5404   5.0  287.0   
326  0.30347   0.0   7.38   0.0  0.493  6.312  28.9  5.4159   5.0  287.0   

     PTRATIO       B  LSTAT  MEDV        TPRM  
254     16.4  392.89   6.57  21.9   51.571709  
348     17.0  390.94   5.99  24.5   42.200452  
476     20.2  396.21  18.68  16.7  102.714374  
321     19.6  396.90   6.87  23.1   45.012547  
326     19.6  396.90   6.15  23.0   45.468948

In [53]:
corr_matrix = housing.corr()

corr_matrix


CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.212927  0.416640 -0.061482  0.430879 -0.256843  0.361890   
ZN      -0.212927  1.000000 -0.542161 -0.023536 -0.509327  0.292010 -0.565680   
INDUS    0.416640 -0.542161  1.000000  0.043686  0.759051 -0.382166  0.644114   
CHAS    -0.061482 -0.023536  0.043686  1.000000  0.077490  0.100672  0.058388   
NOX      0.430879 -0.509327  0.759051  0.077490  1.000000 -0.299416  0.727358   
RM      -0.256843  0.292010 -0.382166  0.100672 -0.299416  1.000000 -0.240747   
AGE      0.361890 -0.565680  0.644114  0.058388  0.727358 -0.240747  1.000000   
DIS     -0.386900  0.666939 -0.708612 -0.088081 -0.763623  0.202010 -0.734827   
RAD      0.648221 -0.306480  0.580908 -0.023005  0.596012 -0.198916  0.449489   
TAX      0.603934 -0.322803  0.716288 -0.048802  0.659049 -0.280938  0.501491   
PTRATIO  0.305603 -0.390570  0.384465 -0.132682  0.164977 -0.329776  0.259633   
B       -0.486869  0.188575 -0.368685  0.048275 -0.408434  0.121794 -0.287900   
LSTAT    0.471442 -0.420097  0.611068 -0.077592  0.602386 -0.601693  0.599211   
MEDV    -0.393715  0.339741 -0.473516  0.205066 -0.422873  0.680262 -0.364596   
TPRM     0.622071 -0.342292  0.714931 -0.069876  0.658245 -0.510355  0.507368   

              DIS       RAD       TAX   PTRATIO         B     LSTAT      MEDV  \
CRIM    -0.386900  0.648221  0.603934  0.305603 -0.486869  0.471442 -0.393715   
ZN       0.666939 -0.306480 -0.322803 -0.390570  0.188575 -0.420097  0.339741   
INDUS   -0.708612  0.580908  0.716288  0.384465 -0.368685  0.611068 -0.473516   
CHAS    -0.088081 -0.023005 -0.048802 -0.132682  0.048275 -0.077592  0.205066   
NOX     -0.763623  0.596012  0.659049  0.164977 -0.408434  0.602386 -0.422873   
RM       0.202010 -0.198916 -0.280938 -0.329776  0.121794 -0.601693  0.680262   
AGE     -0.734827  0.449489  0.501491  0.259633 -0.287900  0.599211 -0.364596   
DIS      1.000000 -0.481556 -0.530840 -0.215173  0.309222 -0.501408  0.240451   
RAD     -0.481556  1.000000  0.910932  0.471912 -0.490951  0.479857 -0.374693   
TAX     -0.530840  0.910932  1.000000  0.473026 -0.475293  0.534228 -0.456657   
PTRATIO -0.215173  0.471912  0.473026  1.000000 -0.193293  0.370759 -0.493534   
B        0.309222 -0.490951 -0.475293 -0.193293  1.000000 -0.405799  0.361761   
LSTAT   -0.501408  0.479857  0.534228  0.370759 -0.405799  1.000000 -0.740494   
MEDV     0.240451 -0.374693 -0.456657 -0.493534  0.361761 -0.740494  1.000000   
TPRM    -0.532236  0.861794  0.953635  0.478174 -0.444678  0.614541 -0.525227   

             TPRM  
CRIM     0.622071  
ZN      -0.342292  
INDUS    0.714931  
CHAS    -0.069876  
NOX      0.658245  
RM      -0.510355  
AGE      0.507368  
DIS     -0.532236  
RAD      0.861794  
TAX      0.953635  
PTRATIO  0.478174  
B       -0.444678  
LSTAT    0.614541  
MEDV    -0.525227  
TPRM     1.000000

In [54]:
corr_matrix["MEDV"].sort_values(ascending = False)

## Strong Positive Corrilation = 1
## Strong Negative Corrilation = -1

MEDV       1.000000
RM         0.680262
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
TPRM      -0.525227
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [55]:
housing

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
254  0.04819  80.0   3.64   0.0  0.392  6.108  32.0  9.2203   1.0  315.0   
348  0.01501  80.0   2.01   0.0  0.435  6.635  29.7  8.3440   4.0  280.0   
476  4.87141   0.0  18.10   0.0  0.614  6.484  93.6  2.3053  24.0  666.0   
321  0.18159   0.0   7.38   0.0  0.493  6.376  54.3  4.5404   5.0  287.0   
326  0.30347   0.0   7.38   0.0  0.493  6.312  28.9  5.4159   5.0  287.0   
..       ...   ...    ...   ...    ...    ...   ...     ...   ...    ...   
155  3.53501   0.0  19.58   1.0  0.871  6.152  82.6  1.7455   5.0  403.0   
423  7.05042   0.0  18.10   0.0  0.614  6.103  85.1  2.0218  24.0  666.0   
98   0.08187   0.0   2.89   0.0  0.445  7.820  36.9  3.4952   2.0  276.0   
455  4.75237   0.0  18.10   0.0  0.713  6.525  86.5  2.4358  24.0  666.0   
216  0.04560   0.0  13.89   1.0  0.550  5.888  56.0  3.1121   5.0  276.0   

     PTRATIO       B  LSTAT  MEDV        TPRM  
254     16.4  392.89   6.57  21.9   51.571709  
348     17.0  390.94   5.99  24.5   42.200452  
476     20.2  396.21  18.68  16.7  102.714374  
321     19.6  396.90   6.87  23.1   45.012547  
326     19.6  396.90   6.15  23.0   45.468948  
..       ...     ...    ...   ...         ...  
155     14.7   88.01  15.02  15.6   65.507152  
423     20.2    2.52  23.29  13.4  109.126659  
98      18.0  393.53   3.57  43.8   35.294118  
455     20.2   50.92  18.13  14.1  102.068966  
216     16.4  392.80  13.51  23.3   46.875000  

[404 rows x 15 columns]

In [56]:
# housing.plot(kind="scatter",x = "TPRM", y = "MEDV", alpha = 1)

In [57]:
housing_labels = strat_train_index.MEDV.copy()
housing = strat_train_index.drop("MEDV",axis = 1)

# Feature Scalling

Feature Scalling has Primirily 2 types,
1. Normalization - (MinMax Scalling)
    Normalization = (value - min) / (max - min)
    
    Sklearn has class as MinMaxScaler 
    
2. Standardization
    Standardization = (value - mean) / (std)
    
    Sklearn has class as StandardScaler   
    
Using Standardization will be helpfull, beacause it uses mean and standard deviation; Even if max or min value eleminate from data will not affect the data that much; But if we use Normalization and removed min or max value then Data will <b>Drasstically</b>
affects.

# Scikit-learn Design

## Create Pipeline

In [58]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [59]:
my_pipeline = Pipeline([
    ("imputer",SimpleImputer(strategy="median")),
    ("std_Scaler",StandardScaler()),
])

In [60]:
Housing_Data = my_pipeline.fit_transform(housing)
Housing_Data

array([[-0.43942006,  3.12628155, -1.12165014, ..., -0.97491834,
         0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, ..., -0.69277865,
         0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, ...,  0.81196637,
         0.44624347,  0.81480158],
       ...,
       [-0.43525657, -0.4898311 , -1.23083158, ..., -0.22254583,
         0.41831233, -1.27603303],
       [ 0.14210728, -0.4898311 ,  0.98336806, ...,  0.81196637,
        -3.15239177,  0.73869575],
       [-0.43974024, -0.4898311 ,  0.37049623, ..., -0.97491834,
         0.41070422,  0.09940681]])

In [61]:
Housing_Data.shape

(404, 13)

## Selecting a desired model for Dragon Real Estate 

In [62]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

# model = LinearRegression()
# model = DecisionTreeRegressor()
model = RandomForestRegressor()
model.fit(Housing_Data,housing_labels)

RandomForestRegressor()

In [63]:
some_data = housing.iloc[:5]
some_labels = housing_labels.iloc[:5]
prep_data = my_pipeline.transform(some_data)
model.predict(prep_data)

array([22.463, 25.471, 16.331, 23.488, 23.459])

# Evaluating model

In [64]:
import numpy as np
np.array(some_labels)

array([21.9, 24.5, 16.7, 23.1, 23. ])

In [65]:
from sklearn.metrics import mean_squared_error
housing_predict = model.predict(Housing_Data)
mean_sq_error = mean_squared_error(housing_labels,housing_predict)
root_mean_sqrt_error = np.sqrt(mean_sq_error)
root_mean_sqrt_error

1.1624423652273028

# Using better evaluation technique - Cross validation

In [66]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(model,Housing_Data,housing_labels,scoring="neg_mean_squared_error",cv=10)
rmse_scores = np.sqrt(- score)

In [67]:
rmse_scores

array([2.77807664, 2.71465299, 4.37452181, 2.53056018, 3.33030689,
       2.62903042, 4.76386489, 3.33368483, 3.34866974, 3.20104098])

In [68]:
def print_value(scores,model)-> str: 
    return(f"Model:{str(model)[:-2]}\nMean: {scores.mean()}\nStandard Deviation: {scores.std()}")

In [69]:
Model_Output = print_value(rmse_scores,model)
Model_Output
# print(Model_Output)
with open('Models_Output.txt', 'a') as the_file:
    the_file.write("\n\n"+Model_Output)

In [71]:
from joblib import dump,load
dump(model,"Dragon.joblib") # Model saved.

['Dragon.joblib']

# Model Testing on test data

In [73]:
X_test = strat_test_index.drop("MEDV",axis = 1)
Y_test = strat_test_index.MEDV

X_test_Prep = my_pipeline.transform(X_test)
Final_predictions = model.predict(X_test_Prep)

Final_mse = mean_squared_error(Y_test,Final_predictions)
Final_rmse = np.sqrt(Final_mse)

In [74]:
Final_rmse

2.913756414180236

In [75]:
Final_predictions

array([24.635, 11.696, 25.376, 21.952, 18.188, 15.059, 19.856, 14.44 ,
       31.377, 40.719, 19.719, 11.587, 24.298, 28.711, 19.653, 10.546,
       31.726, 14.585, 23.659, 18.968, 19.743, 18.077, 17.27 , 22.076,
       17.982, 30.7  , 16.283, 32.668,  8.753, 33.742, 23.804, 21.4  ,
       22.803, 10.995, 21.041, 11.317, 42.764, 24.328, 23.043, 41.461,
       24.03 , 29.507, 20.585, 21.013, 19.366, 33.508, 44.404, 20.201,
       20.374, 21.698, 21.481, 14.471, 20.983, 14.956, 24.91 , 32.639,
       42.928, 28.455, 19.114, 20.957, 47.412, 10.018, 18.818, 24.396,
       14.97 , 32.847, 19.235, 18.057, 19.022, 34.217, 27.133, 22.737,
       21.519, 22.18 , 35.134, 12.734, 15.851, 20.023, 20.807, 21.461,
       22.299, 21.396, 14.364, 22.709, 20.696, 21.137, 13.988, 21.344,
       21.341, 23.523, 18.871, 27.295,  7.13 , 26.144, 19.02 , 29.949,
       19.783, 31.244, 14.513, 26.362, 20.877, 20.047])

In [77]:
np.array(Y_test)

array([16.5, 10.2, 30.1, 23. , 14.4, 15.6, 19.4, 14.1, 30.3, 35.2, 23.1,
       13.8, 25. , 27.9, 19.5, 12.3, 32.2, 13.5, 23.8, 21.7, 19.2, 19.5,
       10.4, 23.2, 18.6, 28.5, 15.2, 32. ,  7.2, 34.6, 20.1, 20.6, 23.6,
       13.1, 23.8, 12.7, 43.1, 24.7, 22.2, 44. , 28.1, 31. , 21.7, 23.4,
       19.5, 33.1, 41.7, 18.7, 19.9, 20.6, 21.2, 13.6, 20.3, 17.8, 27.1,
       31.5, 50. , 29.1, 18.9, 20.4, 50. ,  7.2, 17.2, 36.2, 14.6, 33.2,
       23.8, 19.9, 21.5, 37.3, 27. , 22. , 24.3, 19.8, 33.3,  7. , 19.4,
       20.9, 21.1, 20.4, 22.2, 11.9, 11.7, 21.6, 19.7, 23. , 16.7, 21.7,
       20.6, 23.3, 19.6, 28. ,  5. , 24.4, 20.8, 24.8, 21.8, 23.6, 19. ,
       25. , 20.3, 21.5])